#!/bin/bash
clear

# Some colors
GREEN='\033[0;32m'
NONE='\033[0m'

# Header
echo -e "${GREEN}"
cat <<"EOF"
 _   _       _           _        _ _           
| | | |_ __ (_)_ __  ___| |_ __ _| | | ___ _ __ 
| | | | '_ \| | '_ \/ __| __/ _` | | |/ _ \ '__|
| |_| | | | | | | | \__ \ || (_| | | |  __/ |   
 \___/|_| |_|_|_| |_|___/\__\__,_|_|_|\___|_|   
                                                
EOF
echo "for ML4W Dotfiles"
echo
echo -e "${NONE}"
echo "This script will support you to uninstall the ML4W Dotfiles from your system."
echo "Only the ML4W Dotfiles related files and folders will be removed."
echo "Packages will not be uninstalled. You have to uninstall packages manually if needed."
echo "Your login manager (display manager) will stay untouched. Please remove it manually if needed."

if gum confirm "DO YOU WANT TO START THE UNINSTALLATION NOW?" ;then
    echo ":: Uninstallation started."
elif [ $? -eq 130 ]; then
    echo ":: Uninstallation canceled."
    exit 130
else
    echo ":: Uninstallation canceled."
    exit
fi

if gum confirm "DO YOU WANT TO CREATE A BACKUP OF YOUR DOTFILES?" ;then
    echo ":: Backup created."
elif [ $? -eq 130 ]; then
    echo ":: Uninstallation canceled."
    exit 130
else
    echo ":: Backup Skipped."
    exit
fi

echo ":: $HOME/dotfiles removed"
echo ":: Symlinks removed"
echo ":: ML4W Apps removed"

if gum confirm "DO YOU WANT TO RESTORE OLD CONFIGURATIONS FROM ~/dotfiles-versions/backup/config TO ~/.config?" ;then
    echo ":: Old configuration files restored in .config."
elif [ $? -eq 130 ]; then
    echo ":: Uninstallation canceled."
    exit 130
else
    echo ":: .config restore skipped."
    exit
fi

if gum confirm "DO YOU WANT TO KEEP ~/dotfiles-version WITH ALL BACKUPS?" ;then
    echo ":: You will find the folder dotfiles-versions including your backups in your HOME folder."
elif [ $? -eq 130 ]; then
    echo ":: Uninstallation canceled."
    exit 130
else
    echo ":: $HOME/dotfiles-versions folder removed"
    exit
fi

figlet "DONE"
echo ":: The ML4W Dotfiles have been removed."
echo ":: SEE YOU NEXT TIME ;-) "
