#!/bin/bash
clear

# Some colors
GREEN='\033[0;32m'
NONE='\033[0m'

# Header
echo -e "${GREEN}"
cat <<"EOF"
 _   _       _           _        _ _           
| | | |_ __ (_)_ __  ___| |_ __ _| | | ___ _ __ 
| | | | '_ \| | '_ \/ __| __/ _` | | |/ _ \ '__|
| |_| | | | | | | | \__ \ || (_| | | |  __/ |   
 \___/|_| |_|_|_| |_|___/\__\__,_|_|_|\___|_|   
                                                
EOF
echo "for ML4W Dotfiles"
echo
echo -e "${NONE}"
echo "This script will support you to uninstall the ML4W Dotfiles from your system."
echo "Only the ML4W Dotfiles related files and folders will be removed."
echo "Packages will not be uninstalled. You have to uninstall packages manually if needed."
echo "Your login manager (display manager) will stay untouched. Please remove it manually if needed."

if gum confirm "DO YOU WANT TO START THE UNINSTALLATION NOW?" ;then
    echo ":: Uninstallation started."
elif [ $? -eq 130 ]; then
    echo ":: Uninstallation canceled."
    exit 130
else
    echo ":: Uninstallation canceled."
    exit
fi

if gum confirm "DO YOU WANT TO CREATE A BACKUP OF YOUR DOTFILES?" ;then
    rsync -a ~/dotfiles ~/dotfiles-versions/backup/
    echo ":: Backup of $HOME/dotfiles created in ~/dotfiles-versions/backup"
elif [ $? -eq 130 ]; then
    echo ":: Uninstallation canceled."
    exit 130
else
    echo ":: Backup Skipped."
fi

rm -rf $HOME/dotfiles
echo ":: $HOME/dotfiles removed"

if test -L ~/.bashrc ;then
    rm $HOME/.bashrc
fi
if test -L ~/.config/qtile ;then
    rm $HOME/.config/qtile
fi
if test -L ~/.config/hypr ;then
    rm $HOME/.config/hypr
fi
if test -L ~/.config/fastfetch ;then
    rm $HOME/.config/fastfetch
fi
if test -L ~/.config/rofi ;then
    rm $HOME/.config/rofi
fi
if test -L ~/.config/wal ;then
    rm $HOME/.config/wal
fi
if test -L ~/.config/waybar ;then
    rm $HOME/.config/waybar
fi
if test -L ~/.config/wlogout ;then
    rm $HOME/.config/wlogout
fi
if test -L ~/.config/alacritty ;then
    rm $HOME/.config/alacritty
fi
if test -L ~/.config/starship ;then
    rm $HOME/.config/starship
fi
if test -L ~/.config/picom ;then
    rm $HOME/.config/picom
fi
if test -L ~/.config/nvim ;then
    rm $HOME/.config/nvim
fi
if test -L ~/.config/vim ;then
    rm $HOME/.config/vim
fi
if test -L ~/.config/dunst ;then
    rm $HOME/.config/dunst
fi
if test -L ~/.config/swappy ;then
    rm $HOME/.config/swappy
fi
echo ":: Symlinks removed"

rm $HOME/.local/share/applications/ml4w-dotfiles-settings.desktop
rm $HOME/.local/share/applications/ml4w-welcome.desktop
rm $HOME/.local/share/applications/ml4w-hyprland-settings.desktop
echo ":: ML4W Apps removed"

if gum confirm "DO YOU WANT TO RESTORE OLD CONFIGURATIONS FROM ~/dotfiles-versions/backup/config TO ~/.config?" ;then
    rsync -a ~/dotfiles-versions/backup/config/ ~/.config/
    echo ":: Old configuration files restored in .config."
elif [ $? -eq 130 ]; then
    echo ":: Uninstallation canceled."
    exit 130
else
    echo ":: .config restore skipped."
    exit
fi

if gum confirm "DO YOU WANT TO KEEP ~/dotfiles-version WITH ALL BACKUPS?" ;then
    echo ":: You will find the folder dotfiles-versions including your backups in your HOME folder."
elif [ $? -eq 130 ]; then
    echo ":: Uninstallation canceled."
    exit 130
else
    rm -rf $HOME/dotfiles-versions
    echo ":: $HOME/dotfiles-versions folder removed"
    exit
fi

figlet "DONE"
echo ":: The ML4W Dotfiles have been removed."
gum spin --spinner dot --title ":: SEE YOU NEXT TIME ;-)" -- sleep 3
